use_frameworks!

platform :ios, '9.0'

target 'RobotMapViewStatic_Example' do
  pod 'RobotMapViewStatic', :path => '../'

  target 'RobotMapViewStatic_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
